nameOverride: ""
fullnameOverride: ""

deployment:
  image:
    repository: xhofe/alist-aria2
    tag: "v3.16.3"
    pullPolicy: IfNotPresent

  resources: {}
  secrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraEnvVars: []

service:
  type: ClusterIP
  port: 5244
  targetPort: 5244

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  path: /opt/alist/data
  #storageClass:
  #existingClaim:

securityContext:
  enabled: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

ingress:
  enabled: false
  className: nginx
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ssl-redirect: "true"
  hosts:
    - alist.domain.tld
  tls:
   - secretName: alist-tls-secret
     hosts:
       - alist.domain.tld