apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.fullname" . }}-sa-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mssql.name" . }}
    helm.sh/chart: {{ include "mssql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
 sa_password : {{ .Values.mssql.saPassword | b64enc | quote}}